spring:
  # Database Configuration - File-based H2 Database
  datasource:
    url: jdbc:h2:file:./data/todolist_dev # Creates database files in ./data/ folder
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 Console (for viewing database in browser)
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update # Creates/updates tables automatically
    show-sql: true # Shows SQL queries in console
    properties:
      hibernate:
        format_sql: true # Pretty-prints SQL
        dialect: org.hibernate.dialect.H2Dialect

  # Server Configuration
server:
  port: ${SERVER_PORT:8080}

# Logging Configuration
logging:
  file:
    name: logs/app.log
  level:
    com.mytodolist: DEBUG # Your app packages
    org.springframework.web: DEBUG # Spring web requests
    org.hibernate.SQL: DEBUG # SQL queries
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.hibernate.type: TRACE # SQL parameters
    root: INFO # Default logging level
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
